# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31b508bc46bba9d63e77c9bd798124d88744eb1559066c8b8aefb6c99d4eb18174b7673a8ab089bf1b8c4951cc3b00a0456523319a84e5b2d11510cd61d13a93

test:
  secret_key_base: 5723b3301cb96c8e781cf2a33fdce3df9d4ebc64e4da6d3ed8974da22dc12e1acd7e44e2fea4b2c8a5b020034aff1da3510adad5e618270b22d34e4c0bc8e633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
